"""job_hunter_profile_contact_fields

Revision ID: 149731ecb709
Revises: e8e231f1f419
Create Date: 2026-04-11 19:41:23.063323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149731ecb709'
down_revision: Union[str, Sequence[str], None] = 'e8e231f1f419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_hunter_profiles', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('job_hunter_profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('job_hunter_profiles', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('job_hunter_profiles', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('job_hunter_profiles', sa.Column('country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_hunter_profiles', 'country')
    op.drop_column('job_hunter_profiles', 'city')
    op.drop_column('job_hunter_profiles', 'phone')
    op.drop_column('job_hunter_profiles', 'email')
    op.drop_column('job_hunter_profiles', 'full_name')
    # ### end Alembic commands ###
