"""add linkedin_account_encrypted to campaigns

Revision ID: 2c7b9e8bf9db
Revises: 00598e93a3b5
Create Date: 2026-04-14 19:28:34.496691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7b9e8bf9db'
down_revision: Union[str, Sequence[str], None] = '00598e93a3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_hunter_campaigns', sa.Column('linkedin_account_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_hunter_campaigns', 'linkedin_account_encrypted')
    # ### end Alembic commands ###
