"""add_campaign_activity_log

Revision ID: 36b86f36ceba
Revises: e1e75f3b2ab0
Create Date: 2026-04-13 13:07:40.741352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b86f36ceba'
down_revision: Union[str, Sequence[str], None] = 'e1e75f3b2ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_activity_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['job_hunter_campaigns.id'], name=op.f('fk_campaign_activity_log_campaign_id_job_hunter_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_activity_log'))
    )
    op.create_index('ix_campaign_activity_log_campaign', 'campaign_activity_log', ['campaign_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaign_activity_log_campaign', table_name='campaign_activity_log')
    op.drop_table('campaign_activity_log')
    # ### end Alembic commands ###
