"""job_hunter_schema

Revision ID: 6d85fe7a3395
Revises: f28492caa76f
Create Date: 2026-04-11 19:25:50.214884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d85fe7a3395'
down_revision: Union[str, Sequence[str], None] = 'f28492caa76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('job_listing_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tailored_resume_pdf_url', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('form_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('ix_applications_campaign', 'applications', ['campaign_id'], unique=False)
    op.create_index('ix_applications_job_listing', 'applications', ['job_listing_id'], unique=False)
    op.create_index('ix_applications_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('email_event_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('calendar_provider', sa.String(length=20), nullable=False),
    sa.Column('external_event_id', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_events'))
    )
    op.create_index('ix_calendar_events_application', 'calendar_events', ['application_id'], unique=False)
    op.create_table('email_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('ai_reply_sent', sa.Boolean(), nullable=False),
    sa.Column('ai_reply_body', sa.Text(), nullable=True),
    sa.Column('ai_reply_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_events'))
    )
    op.create_index('ix_email_events_application', 'email_events', ['application_id'], unique=False)
    op.create_index('ix_email_events_campaign_type', 'email_events', ['campaign_id', 'type'], unique=False)
    op.create_table('job_hunter_campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broad_category', sa.String(length=255), nullable=False),
    sa.Column('sub_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_account_encrypted', sa.Text(), nullable=True),
    sa.Column('caldav_account_encrypted', sa.Text(), nullable=True),
    sa.Column('email_monitor_since', sa.DateTime(), nullable=True),
    sa.Column('schedule_interval_hours', sa.Integer(), nullable=False),
    sa.Column('user_country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_hunter_campaigns'))
    )
    op.create_index('ix_jh_campaigns_user_id', 'job_hunter_campaigns', ['user_id'], unique=False)
    op.create_index('ix_jh_campaigns_user_status', 'job_hunter_campaigns', ['user_id', 'status'], unique=False)
    op.create_table('job_hunter_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('completion_score', sa.Integer(), nullable=False),
    sa.Column('work_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('languages_spoken', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_hunter_profiles'))
    )
    op.create_index(op.f('ix_job_hunter_profiles_user_id'), 'job_hunter_profiles', ['user_id'], unique=False)
    op.create_table('job_listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('location_country', sa.String(length=2), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('match_score', sa.String(length=10), nullable=True),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_listings')),
    sa.UniqueConstraint('url_hash', name='uq_job_listings_url_hash')
    )
    op.create_index('ix_job_listings_campaign_category', 'job_listings', ['campaign_id', 'sub_category'], unique=False)
    op.create_index('ix_job_listings_campaign_status', 'job_listings', ['campaign_id', 'status'], unique=False)
    op.create_index('ix_job_listings_url_hash', 'job_listings', ['url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_listings_url_hash', table_name='job_listings')
    op.drop_index('ix_job_listings_campaign_status', table_name='job_listings')
    op.drop_index('ix_job_listings_campaign_category', table_name='job_listings')
    op.drop_table('job_listings')
    op.drop_index(op.f('ix_job_hunter_profiles_user_id'), table_name='job_hunter_profiles')
    op.drop_table('job_hunter_profiles')
    op.drop_index('ix_jh_campaigns_user_status', table_name='job_hunter_campaigns')
    op.drop_index('ix_jh_campaigns_user_id', table_name='job_hunter_campaigns')
    op.drop_table('job_hunter_campaigns')
    op.drop_index('ix_email_events_campaign_type', table_name='email_events')
    op.drop_index('ix_email_events_application', table_name='email_events')
    op.drop_table('email_events')
    op.drop_index('ix_calendar_events_application', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index('ix_applications_user_status', table_name='applications')
    op.drop_index('ix_applications_job_listing', table_name='applications')
    op.drop_index('ix_applications_campaign', table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
