"""job_listings_match_score_string

Revision ID: d2094363371c
Revises: 149731ecb709
Create Date: 2026-04-11 19:55:25.488128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2094363371c'
down_revision: Union[str, Sequence[str], None] = '149731ecb709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_listings', 'match_score',
               existing_type=sa.Float(),
               type_=sa.String(length=10),
               existing_nullable=True,
               postgresql_using='NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_listings', 'match_score',
               existing_type=sa.String(length=10),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
