"""user_integrations_table_campaign_toggles

Revision ID: da25c747a61b
Revises: 2c7b9e8bf9db
Create Date: 2026-04-15 01:35:26.544569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da25c747a61b'
down_revision: Union[str, Sequence[str], None] = '2c7b9e8bf9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email_account_encrypted', sa.Text(), nullable=True),
    sa.Column('caldav_account_encrypted', sa.Text(), nullable=True),
    sa.Column('linkedin_account_encrypted', sa.Text(), nullable=True),
    sa.Column('email_monitor_since', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_integrations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_integrations')),
    sa.UniqueConstraint('user_id', name='uq_user_integrations_user_id')
    )
    op.create_index('ix_user_integrations_user_id', 'user_integrations', ['user_id'], unique=False)
    op.add_column('job_hunter_campaigns', sa.Column('email_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('job_hunter_campaigns', sa.Column('caldav_enabled', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('job_hunter_campaigns', sa.Column('linkedin_enabled', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_hunter_campaigns', 'linkedin_enabled')
    op.drop_column('job_hunter_campaigns', 'caldav_enabled')
    op.drop_column('job_hunter_campaigns', 'email_enabled')
    op.drop_index('ix_user_integrations_user_id', table_name='user_integrations')
    op.drop_table('user_integrations')
    # ### end Alembic commands ###
