"""add career context columns to sessions

Revision ID: e2d6677a2135
Revises: b1c2d3e4f5a6
Create Date: 2026-05-14 13:26:23.014953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2d6677a2135'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('track', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_profiles')),
    sa.UniqueConstraint('track', 'level', 'stage', name='uq_knowledge_profile')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('career_track', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('skill_dimension', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_user_progress_session_id_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_progress'))
    )
    op.drop_index('ix_cluely_transcript_lines_session_id', table_name='cluely_transcript_lines')
    op.drop_table('cluely_transcript_lines')
    op.drop_index('ix_cluely_interactions_session_id', table_name='cluely_interactions')
    op.drop_table('cluely_interactions')
    op.drop_index('ix_cluely_sessions_application_id', table_name='cluely_sessions')
    op.drop_index('ix_cluely_sessions_user_id', table_name='cluely_sessions')
    op.drop_table('cluely_sessions')
    op.add_column('sessions', sa.Column('career_track', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('level', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('interview_stage', sa.String(length=100), nullable=True))
    op.add_column('sessions', sa.Column('jd_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'jd_hash')
    op.drop_column('sessions', 'interview_stage')
    op.drop_column('sessions', 'level')
    op.drop_column('sessions', 'career_track')
    op.create_table('cluely_interactions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trigger_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inferred_outcome', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['cluely_sessions.id'], name='fk_cluely_interactions_session_id_cluely_sessions'),
    sa.PrimaryKeyConstraint('id', name='pk_cluely_interactions')
    )
    op.create_index('ix_cluely_interactions_session_id', 'cluely_interactions', ['session_id'], unique=False)
    op.create_table('cluely_transcript_lines',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('speaker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spoken_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['cluely_sessions.id'], name='fk_cluely_transcript_lines_session_id_cluely_sessions'),
    sa.PrimaryKeyConstraint('id', name='pk_cluely_transcript_lines')
    )
    op.create_index('ix_cluely_transcript_lines_session_id', 'cluely_transcript_lines', ['session_id'], unique=False)
    op.create_table('cluely_sessions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('session_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tools_used', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_cluely_sessions_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_cluely_sessions')
    )
    op.create_index('ix_cluely_sessions_user_id', 'cluely_sessions', ['user_id'], unique=False)
    op.create_index('ix_cluely_sessions_application_id', 'cluely_sessions', ['application_id'], unique=False)
    op.drop_table('user_progress')
    op.drop_table('knowledge_profiles')
    # ### end Alembic commands ###
