"""job_hunter_schema_fk_constraints

Revision ID: e8e231f1f419
Revises: 6d85fe7a3395
Create Date: 2026-04-11 19:33:45.826573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e231f1f419'
down_revision: Union[str, Sequence[str], None] = '6d85fe7a3395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_applications_campaign_id_job_hunter_campaigns'), 'applications', 'job_hunter_campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(op.f('fk_applications_job_listing_id_job_listings'), 'applications', 'job_listings', ['job_listing_id'], ['id'])
    op.create_foreign_key(op.f('fk_applications_user_id_users'), 'applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_calendar_events_application_id_applications'), 'calendar_events', 'applications', ['application_id'], ['id'])
    op.create_foreign_key(op.f('fk_calendar_events_email_event_id_email_events'), 'calendar_events', 'email_events', ['email_event_id'], ['id'])
    op.create_foreign_key(op.f('fk_email_events_campaign_id_job_hunter_campaigns'), 'email_events', 'job_hunter_campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(op.f('fk_email_events_application_id_applications'), 'email_events', 'applications', ['application_id'], ['id'])
    op.create_foreign_key(op.f('fk_job_hunter_campaigns_user_id_users'), 'job_hunter_campaigns', 'users', ['user_id'], ['id'])
    op.add_column('job_hunter_profiles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint('uq_job_hunter_profiles_user_id', 'job_hunter_profiles', ['user_id'])
    op.create_foreign_key(op.f('fk_job_hunter_profiles_user_id_users'), 'job_hunter_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('job_listings', 'match_score',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Float(),
               existing_nullable=True,
               postgresql_using='match_score::double precision')
    op.create_foreign_key(op.f('fk_job_listings_campaign_id_job_hunter_campaigns'), 'job_listings', 'job_hunter_campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_job_listings_campaign_id_job_hunter_campaigns'), 'job_listings', type_='foreignkey')
    op.alter_column('job_listings', 'match_score',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_job_hunter_profiles_user_id_users'), 'job_hunter_profiles', type_='foreignkey')
    op.drop_constraint('uq_job_hunter_profiles_user_id', 'job_hunter_profiles', type_='unique')
    op.drop_column('job_hunter_profiles', 'created_at')
    op.drop_constraint(op.f('fk_job_hunter_campaigns_user_id_users'), 'job_hunter_campaigns', type_='foreignkey')
    op.drop_constraint(op.f('fk_email_events_application_id_applications'), 'email_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_email_events_campaign_id_job_hunter_campaigns'), 'email_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_calendar_events_email_event_id_email_events'), 'calendar_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_calendar_events_application_id_applications'), 'calendar_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_applications_user_id_users'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('fk_applications_job_listing_id_job_listings'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('fk_applications_campaign_id_job_hunter_campaigns'), 'applications', type_='foreignkey')
    # ### end Alembic commands ###
